import { useEffect, useMemo, useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";

import { VGScreen } from "@/components/layout/VGScreen";
import { VGCard, VGEmptyStateView, VGPrimaryButton } from "@/components/ui";
import { VerseRow } from "@/features/bible/VerseRow";
import { useBibleRepository } from "@/features/bible/useBibleRepository";
import { usePersonalVerse } from "@/providers/PersonalVerseProvider";
import { colors, radius, spacing, typography } from "@/theme/tokens";

export function VerseListDetailScreen() {
  const router = useRouter(); const params = useLocalSearchParams<{ listId?: string }>(); const listId = typeof params.listId === "string" ? params.listId : ""; const { repository } = useBibleRepository(); const { lists, subscribeListItems, removeVerseFromList, updateList, deleteList } = usePersonalVerse(); const [items, setItems] = useState<readonly import("./verseListRepository").VerseListItem[]>([]); const [title, setTitle] = useState(""); const [memo, setMemo] = useState(""); const list = lists.find((item) => item.id === listId);
  useEffect(() => { if (!listId) return undefined; return subscribeListItems(listId, setItems); }, [listId, subscribeListItems]);
  const verses = useMemo(() => repository ? items.flatMap((item) => { const verse = repository.getVerse(item.verseId); return verse ? [{ item, verse }] : []; }) : [], [items, repository]);
  if (!list) return <VGScreen><VGEmptyStateView description="리스트를 찾을 수 없습니다." title="리스트가 없어요" /></VGScreen>;
  const save = async () => { await updateList(list.id, title.trim() || list.title, memo.trim() || list.memo); };
  const remove = (itemId: string) => Alert.alert("말씀을 제거할까요?", "리스트에서만 제거됩니다.", [{ text: "취소", style: "cancel" }, { text: "제거", style: "destructive", onPress: () => void removeVerseFromList(list.id, itemId) }]);
  const destroy = () => Alert.alert("리스트를 삭제할까요?", "리스트와 안의 구절이 함께 삭제됩니다.", [{ text: "취소", style: "cancel" }, { text: "삭제", style: "destructive", onPress: async () => { await deleteList(list.id); router.back(); } }]);
  return <VGScreen><Pressable accessibilityRole="button" onPress={() => router.back()} style={styles.back}><Text style={styles.backLabel}>‹ 리스트</Text></Pressable><VGCard style={styles.form}><Text style={styles.formTitle}>리스트 정보</Text><Text style={styles.currentTitle}>{list.title}</Text>{list.memo ? <Text style={styles.currentMemo}>{list.memo}</Text> : null}<TextInput accessibilityLabel="새 리스트 제목" onChangeText={setTitle} placeholder="제목을 바꾸려면 입력하세요" placeholderTextColor={colors.subtleText} style={styles.input} value={title} /><TextInput accessibilityLabel="새 리스트 메모" onChangeText={setMemo} placeholder="메모를 바꾸려면 입력하세요" placeholderTextColor={colors.subtleText} style={styles.input} value={memo} /><VGPrimaryButton label="수정 저장" onPress={() => void save()} /><Pressable accessibilityRole="button" onPress={destroy} style={styles.deleteButton}><Text style={styles.deleteLabel}>리스트 삭제</Text></Pressable></VGCard>{verses.length === 0 ? <VGEmptyStateView description="말씀 상세에서 이 리스트를 선택하면 구절을 담을 수 있어요." title="아직 담긴 말씀이 없어요" /> : <View style={styles.items}>{verses.map(({ item, verse }) => <View key={item.id} style={styles.item}><VerseRow onPress={(selected) => router.push({ pathname: "/verse/[verseId]", params: { verseId: selected.id } })} verse={verse} /><Pressable accessibilityLabel="리스트에서 말씀 제거" accessibilityRole="button" onPress={() => remove(item.id)} style={styles.remove}><Text style={styles.removeLabel}>제거</Text></Pressable></View>)}</View>}</VGScreen>;
}
const styles = StyleSheet.create({ back: { alignSelf: "flex-start", minHeight: 44, justifyContent: "center" }, backLabel: { color: colors.forestGreen, ...typography.bodyEmphasis }, form: { gap: spacing.sm }, formTitle: { color: colors.primaryText, ...typography.heading }, currentTitle: { color: colors.primaryText, ...typography.bodyEmphasis }, currentMemo: { color: colors.secondaryText, ...typography.caption }, input: { borderColor: colors.border, borderRadius: radius.medium, borderWidth: 1, color: colors.primaryText, minHeight: 48, paddingHorizontal: spacing.md, ...typography.body }, deleteButton: { alignItems: "center", minHeight: 44, justifyContent: "center" }, deleteLabel: { color: colors.destructive, ...typography.label }, items: { gap: spacing.sm }, item: { gap: spacing.xs }, remove: { alignSelf: "flex-end", minHeight: 40, justifyContent: "center", paddingHorizontal: spacing.sm }, removeLabel: { color: colors.destructive, ...typography.label } });
