import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";

import { VGScreen } from "@/components/layout/VGScreen";
import { VGCard, VGEmptyStateView, VGPrimaryButton } from "@/components/ui";
import { useBibleRepository } from "@/features/bible/useBibleRepository";
import { usePersonalVerse } from "@/providers/PersonalVerseProvider";
import { colors, radius, spacing, typography } from "@/theme/tokens";

export function VerseListsScreen() {
  const router = useRouter(); const params = useLocalSearchParams<{ addVerseId?: string }>(); const { repository } = useBibleRepository(); const { lists, createList, addVerseToList } = usePersonalVerse(); const [title, setTitle] = useState(""); const [memo, setMemo] = useState(""); const [isSaving, setIsSaving] = useState(false);
  const targetVerse = repository && typeof params.addVerseId === "string" ? repository.getVerse(params.addVerseId) : null;
  const create = async () => { if (!title.trim()) return; setIsSaving(true); try { await createList(title, memo); setTitle(""); setMemo(""); } finally { setIsSaving(false); } };
  const selectList = async (listId: string) => { if (!targetVerse) { router.push({ pathname: "/verse/lists/[listId]", params: { listId } }); return; } try { const added = await addVerseToList(listId, targetVerse); Alert.alert(added ? "리스트에 추가했어요" : "이미 리스트에 있어요", targetVerse ? `${targetVerse.book} ${targetVerse.chapter}:${targetVerse.verse}` : ""); router.back(); } catch {} };
  return <VGScreen><View style={styles.header}><Text style={styles.title}>{targetVerse ? "리스트에 추가" : "나만의 구절 리스트"}</Text><Text style={styles.subtitle}>{targetVerse ? "말씀을 담을 리스트를 선택하세요." : "자주 읽고 싶은 말씀을 직접 모아둘 수 있어요."}</Text></View><VGCard style={styles.form}><Text style={styles.formTitle}>새 리스트</Text><TextInput accessibilityLabel="리스트 제목" onChangeText={setTitle} placeholder="예: 위로가 되는 말씀" placeholderTextColor={colors.subtleText} style={styles.input} value={title} /><TextInput accessibilityLabel="리스트 메모" onChangeText={setMemo} placeholder="간단한 설명" placeholderTextColor={colors.subtleText} style={styles.input} value={memo} /><VGPrimaryButton disabled={!title.trim() || isSaving} label={isSaving ? "만드는 중..." : "리스트 만들기"} onPress={() => void create()} /></VGCard>{lists.length === 0 ? <VGEmptyStateView description="새 리스트를 만들면 여기에 표시됩니다." title="아직 만든 리스트가 없어요" /> : <View style={styles.list}>{lists.map((list) => <Pressable accessibilityLabel={`${list.title} 리스트 열기`} accessibilityRole="button" key={list.id} onPress={() => void selectList(list.id)} style={({ pressed }) => [styles.listItem, pressed && styles.pressed]}><View><Text style={styles.listTitle}>{list.title}</Text>{list.memo ? <Text style={styles.listMemo}>{list.memo}</Text> : null}</View><Text style={styles.chevron}>›</Text></Pressable>)}</View>}</VGScreen>;
}
const styles = StyleSheet.create({ header: { gap: spacing.xxs }, title: { color: colors.primaryText, ...typography.title }, subtitle: { color: colors.secondaryText, ...typography.body }, form: { gap: spacing.sm }, formTitle: { color: colors.primaryText, ...typography.heading }, input: { borderColor: colors.border, borderRadius: radius.medium, borderWidth: 1, color: colors.primaryText, minHeight: 48, paddingHorizontal: spacing.md, ...typography.body }, list: { gap: spacing.sm }, listItem: { alignItems: "center", backgroundColor: colors.cardBackground, borderColor: colors.border, borderRadius: radius.medium, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", minHeight: 72, padding: spacing.md }, listTitle: { color: colors.primaryText, ...typography.bodyEmphasis }, listMemo: { color: colors.secondaryText, marginTop: spacing.xxs, ...typography.caption }, chevron: { color: colors.forestGreen, fontSize: 28 }, pressed: { opacity: 0.72 } });
