import { Pressable, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";

import { VGScreen } from "@/components/layout/VGScreen";
import { VGCard, VGEmptyStateView } from "@/components/ui";
import { useBibleRepository } from "@/features/bible/useBibleRepository";
import { usePersonalVerse } from "@/providers/PersonalVerseProvider";
import { colors, radius, spacing, typography } from "@/theme/tokens";

import { assignmentVerses, nextIncompleteAssignment, progressForPlan, todayAssignment } from "./writingPlanLogic";

export function WritingPlanDetailScreen() {
  const router = useRouter(); const params = useLocalSearchParams<{ planId?: string }>(); const planID = typeof params.planId === "string" ? params.planId : ""; const { repository } = useBibleRepository(); const { plans, assignmentsByPlan } = usePersonalVerse(); const plan = plans.find((item) => item.id === planID); const assignments = plan ? assignmentsByPlan[plan.id] ?? [] : [];
  if (!plan || !repository) return <VGScreen><VGEmptyStateView description="플랜을 찾을 수 없습니다." title="필사 플랜이 없어요" /></VGScreen>;
  const progress = progressForPlan(plan, assignments); const today = todayAssignment(plan, assignments); const next = today && today.state !== "completed" ? today : nextIncompleteAssignment(plan, assignments); const open = (assignmentId: string) => { const assignment = assignments.find((item) => item.id === assignmentId); if (!assignment) return; const verses = assignmentVerses(repository, assignment); if (!verses.length) return; const index = Math.min(assignment.completionRecordIds.length, verses.length - 1); router.push({ pathname: "/write/[verseId]", params: { verseId: verses[index].id, planId: plan.id, assignmentId: assignment.id, index: String(index) } }); };
  return <VGScreen><Pressable accessibilityRole="button" onPress={() => router.back()} style={styles.back}><Text style={styles.backLabel}>‹ 플랜</Text></Pressable><VGCard style={styles.summary}><Text style={styles.title}>{plan.title}</Text><Text style={styles.subtitle}>{plan.book} {plan.startChapter}–{plan.endChapter}장 · {progress.completed}/{progress.total}일 완료</Text>{next ? <Pressable accessibilityRole="button" onPress={() => open(next.id)} style={styles.today}><Text style={styles.todayText}>{today?.id === next.id ? "오늘 분량 이어가기" : "다음 분량 이어가기"}</Text></Pressable> : <Text style={styles.complete}>플랜을 모두 완료했어요.</Text>}</VGCard><View style={styles.days}>{assignments.map((assignment) => <Pressable accessibilityLabel={`Day ${assignment.dayIndex} ${assignment.state}`} accessibilityRole="button" key={assignment.id} onPress={() => assignment.state !== "completed" && open(assignment.id)} style={({ pressed }) => [styles.day, assignment.state === "completed" && styles.dayComplete, pressed && styles.pressed]}><View><Text style={styles.dayTitle}>Day {assignment.dayIndex}</Text><Text style={styles.dayRange}>{assignment.book} {assignment.startChapter}:{assignment.startVerse}–{assignment.endChapter}:{assignment.endVerse}</Text></View><Text style={styles.dayState}>{assignment.state === "completed" ? "완료" : assignment.state === "missed" ? "지난 분량" : "시작"}</Text></Pressable>)}</View></VGScreen>;
}
const styles = StyleSheet.create({ back: { alignSelf: "flex-start", minHeight: 44, justifyContent: "center" }, backLabel: { color: colors.forestGreen, ...typography.bodyEmphasis }, summary: { gap: spacing.sm }, title: { color: colors.primaryText, ...typography.heading }, subtitle: { color: colors.secondaryText, ...typography.body }, today: { alignItems: "center", backgroundColor: colors.forestGreen, borderRadius: radius.medium, justifyContent: "center", minHeight: 50 }, todayText: { color: colors.cardBackground, ...typography.bodyEmphasis }, complete: { color: colors.forestGreen, ...typography.label }, days: { gap: spacing.sm }, day: { alignItems: "center", backgroundColor: colors.cardBackground, borderColor: colors.border, borderRadius: radius.medium, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", minHeight: 72, padding: spacing.md }, dayComplete: { backgroundColor: colors.cardTint }, dayTitle: { color: colors.primaryText, ...typography.bodyEmphasis }, dayRange: { color: colors.secondaryText, ...typography.caption }, dayState: { color: colors.forestGreen, ...typography.label }, pressed: { opacity: 0.72 } });
